name: Docker

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: blesswinsamuel/github-actions/docker-build-and-push@main
        with:
          # slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          # docker-build-platforms: linux/amd64,linux/arm64
          docker-build-platforms: linux/amd64,linux/arm64

      # - uses: blesswinsamuel/github-actions/trigger-stack-update@main
      #   with:
      #     github-token: ${{ secrets.BLESS_STACK_TRIGGER_GITHUB_TOKEN }}
      #     stack-repo: "lab"
      #     stack-repo-branch: "main"
